package com.bankingmanagement.transactionservice.exception;

public enum ApiErrorCode {
    TRANSACTION_NOT_FOUND,
    TRANSACTION_ALREADY_EXISTS,
    INSUFFICIENT_FUNDS,
    SAME_ACCOUNT_TRANSFER,
    INVALID_TRANSACTION_TYPE,
    INVALID_AMOUNT,
    INVALID_STATUS_TRANSITION,
    TRANSACTION_PROCESSING_FAILED,
    EXTERNAL_SERVICE_ERROR,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR
}
