package com.bankingmanagement.authservice.entity;

/*
╔══════════════════════════════════════════════════════════════════════════════════════════╗
║                                    ROLE ENTITY                                            ║
║                                                                                           ║
║  BUILD ORDER: STEP 3a of 12 (First Entity)                                               ║
║  PREVIOUS STEP: application.yml (configuration)                                           ║
║  NEXT STEP: User.java (depends on this)                                                  ║
║                                                                                           ║
║  WHY ENTITIES COME AFTER CONFIG:                                                         ║
║  - Entities define the database schema                                                    ║
║  - JPA/Hibernate uses config to connect to database                                      ║
║  - Everything else (repos, services) depends on entities                                 ║
║                                                                                           ║
║  WHY ROLE IS FIRST ENTITY:                                                               ║
║  - Role is INDEPENDENT - it doesn't reference any other entity                           ║
║  - User entity has a ManyToMany relationship TO Role                                     ║
║  - You can't reference something that doesn't exist yet                                  ║
║                                                                                           ║
║  DEPENDENCY CHAIN:                                                                        ║
║  Role (no dependencies) → User (needs Role) → RefreshToken (needs User)                  ║
║                                                                                           ║
║  WHAT THIS CLASS DOES:                                                                    ║
║  - Defines the "roles" database table                                                    ║
║  - Contains role names as an enum for type safety                                        ║
║  - Provides role descriptions for documentation                                          ║
║                                                                                           ║
║  TABLE STRUCTURE:                                                                         ║
║  ┌────────────────────────────────────────┐                                              ║
║  │              roles                      │                                              ║
║  ├────────────────────────────────────────┤                                              ║
║  │ id          UUID (PK)                  │                                              ║
║  │ name        VARCHAR(50) UNIQUE         │ ← Enum value (ROLE_USER, etc.)              ║
║  │ description VARCHAR(200)               │ ← Human-readable description                ║
║  └────────────────────────────────────────┘                                              ║
╚══════════════════════════════════════════════════════════════════════════════════════════╝
*/

import jakarta.persistence.*;
import lombok.*;

import java.util.UUID;

/**
 * Role entity representing user roles/authorities in the banking system.
 * 
 * DESIGN DECISIONS:
 * 
 * 1. WHY USE ENUM FOR ROLE NAMES?
 *    - Type safety: Compiler catches typos (ROLE_ADMN won't compile)
 *    - IDE support: Autocomplete shows available roles
 *    - Refactoring: Rename in one place, updates everywhere
 *    - Documentation: All roles visible in one enum
 * 
 * 2. WHY STORE ROLES IN DATABASE (not just enum)?
 *    - Flexibility: Can add roles without code changes (future)
 *    - Audit trail: Can track when roles were created
 *    - Relationships: JPA handles User-Role join table
 * 
 * 3. WHY UUID FOR ID?
 *    - Globally unique (no collision across services)
 *    - Secure (can't guess next ID)
 *    - Consistent with other entities in the project
 * 
 * Common roles: ROLE_USER, ROLE_ADMIN, ROLE_CUSTOMER, ROLE_TELLER, ROLE_MANAGER
 */
@Entity
@Table(name = "roles")  // Explicit table name (could be inferred, but explicit is clearer)
@Getter                  // Lombok: generates all getter methods
@Setter                  // Lombok: generates all setter methods
@NoArgsConstructor       // Lombok: JPA requires no-arg constructor
@AllArgsConstructor      // Lombok: constructor with all fields
@Builder                 // Lombok: enables Role.builder().name(...).build() pattern
public class Role {

    /**
     * Primary Key: UUID auto-generated by JPA.
     * 
     * WHY UUID (not Long)?
     * - No sequential guessing (security)
     * - Works in distributed systems
     * - Matches other services in this project
     * 
     * GenerationType.UUID: JPA generates UUID automatically on persist
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Role name stored as String in database.
     * 
     * @Enumerated(EnumType.STRING):
     * - Stores "ROLE_USER" instead of 0
     * - Readable in database queries
     * - Survives enum reordering
     * 
     * NEVER use EnumType.ORDINAL (stores 0, 1, 2...):
     * - Adding/reordering enum values breaks data
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, unique = true, length = 50)
    private RoleName name;

    /**
     * Human-readable description of what this role allows.
     * Useful for admin UI, audit logs, documentation.
     */
    @Column(length = 200)
    private String description;

    /**
     * Enum defining available roles in the banking system.
     * 
     * NAMING CONVENTION: "ROLE_" prefix
     * - Required by Spring Security's hasRole() method
     * - hasRole("ADMIN") checks for "ROLE_ADMIN" authority
     * - hasAuthority("ROLE_ADMIN") checks exact match
     * 
     * ROLE HIERARCHY (for future implementation):
     * ROLE_ADMIN > ROLE_MANAGER > ROLE_TELLER > ROLE_CUSTOMER > ROLE_USER
     */
    public enum RoleName {
        /** Basic authenticated user - can login, view own profile */
        ROLE_USER,
        
        /** Bank customer - can view accounts, make transfers */
        ROLE_CUSTOMER,
        
        /** Bank teller - can process transactions, help customers */
        ROLE_TELLER,
        
        /** Branch manager - can approve large transactions, manage staff */
        ROLE_MANAGER,
        
        /** System administrator - full access to everything */
        ROLE_ADMIN
    }
}
